server:
  port: 8090
spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
    web-application-type: reactive
services:
  url:
    auth-url: http://localhost:8081
    car-url: http://localhost:8083
    restaurant-url: http://localhost:8082